#!/bin/bash

user_dir="$(pwd)"
my_dir="$(dirname $(readlink -f $0))"

# Get user args from command line
my_args="$*"

# If we have a default.auth file, use it to create $auth_args
auth_args=''
  if [ -f "${user_dir}/default.auth" ]; then auth_args="-auth ${user_dir}/default.auth"
elif [ -f "${my_dir}/default.auth" ]; then auth_args="-auth ${my_dir}/default.auth"
elif [ -f "${my_dir}/src/default.auth" ]; then auth_args="-auth ${my_dir}/src/default.auth"
fi

# Launch src/pbcli.py
cd ${my_dir}/src
./pbcli.py ${auth_args} ${my_args}
cd ${user_dir}

