#!/bin/bash

echo -n "Checking for updates: "
exit_code=0
[ -d "$(dirname $(readlink -f $0))/.git" ] && ( which git >/dev/null ) && (
	(
		git pull | grep 'Already up-to-date.'
		exit_code=$?
		[ "$exit_code" == "0" ] && ( echo "* WARNING: Please review the license file before continuing. The terms and conditions may have changed since the last update!" )
	) || (
		echo "Internal error."
	)
) || (
	echo "Nothing to do (git not found)"
)

exit $exit_code

